# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration - Security-First Review Policy
# Priority: Security > Logic/Correctness > Design Principles

language: "en-US"
early_access: false

# Strict, security-focused tone
tone_instructions: "Security-first reviewer. Priority: 1) Security (OWASP/CWE), 2) Logic/correctness, 3) DRY/YAGNI. Be direct, cite standards."

reviews:
  # Assertive profile for thorough, detailed feedback
  profile: "assertive"

  # Request changes workflow for critical security issues
  request_changes_workflow: true

  # Disable summaries and diagrams
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  poem: false

  # Detailed review status
  review_status: true
  collapse_walkthrough: true

  # Disable extra context features
  changed_files_summary: false
  sequence_diagrams: false

  # Auto-review configuration
  auto_review:
    enabled: true
    auto_incremental_review: true
    drafts: false
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
      - "DO NOT REVIEW"
      - "DRAFT"

  # Path filters - ignore build artifacts and dependencies
  path_filters:
    - "!**/node_modules/**"
    - "!**/lib/**"
    - "!**/build/**"
    - "!**/dist/**"
    - "!**/*.lock"
    - "!**/yarn.lock"
    - "!**/package-lock.json"
    - "!**/Pods/**"
    - "!**/generated/**"
    - "!**/.yarn/**"
    - "!**/DerivedData/**"

  # Security-focused path instructions (max 245 chars each)
  path_instructions:
    # PROTECTED FILES - Changes require maintainer approval
    - path: ".specify/memory/constitution.md"
      instructions: "PROTECTED FILE - REJECT. Constitution changes need separate RFC, maintainer approval outside PR flow, version bump. Do not approve here."

    - path: "AGENTS.md"
      instructions: "PROTECTED FILE - REJECT. AI agent guidelines tied to constitution. Changes need separate governance discussion, not PR approval."

    # TypeScript source - XSS prevention critical
    - path: "src/**/*.{ts,tsx}"
      instructions: "XSS CRITICAL: Block innerHTML without DOMPurify, eval/Function, unsafe href protocols (javascript:, data:). Verify sanitization before render."

    - path: "src/core/**/*.{ts,tsx}"
      instructions: "CORE SECURITY: Require allowlist sanitization, strip event handlers, validate URLs. No platform-specific code per constitution."

    # iOS Native Code
    - path: "**/*.{swift,m,mm,h}"
      instructions: "iOS: Check retain cycles, thread safety for UI, nil handling, NSAttributedString security. No arbitrary HTML interpretation."

    # Android Native Code
    - path: "**/*.{kt,java}"
      instructions: "Android: Check context leaks, main thread UI updates, Spannable security, null safety. No arbitrary HTML interpretation."

    # C++ Code
    - path: "**/*.{cpp,hpp,h}"
      instructions: "C++: Check buffer overflows, memory leaks, null derefs, RAII patterns. Verify string handling is bounds-checked."

    # Test files
    - path: "**/*.test.{ts,tsx,swift,kt}"
      instructions: "Tests: Verify security test coverage for auth/sanitization. Check assertions are meaningful. Flag duplicated setup code."

    # Configuration files
    - path: "*.{json,yaml,yml}"
      instructions: "Config: Check for exposed secrets/API keys, secure defaults, no debug settings in prod. Validate dependency versions."

    # GitHub workflows
    - path: ".github/workflows/**/*.{yml,yaml}"
      instructions: "CI/CD: Verify secrets handling, least-privilege permissions, pinned action versions, no untrusted code execution."

    # Package dependencies
    - path: "package*.json"
      instructions: "Deps: Flag known vulnerabilities, outdated security patches, typosquatting risks. Minimize attack surface."

  # Enable security and quality tools
  tools:
    github-checks:
      enabled: true
    shellcheck:
      enabled: true
    biome:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    semgrep:
      enabled: true
    checkov:
      enabled: true

  # Disable auto-generated content
  finishing_touches:
    docstrings:
      enabled: false
    unit_tests:
      enabled: false
  auto_title_placeholder: "@coderabbitai title"
  assess_linked_issues: true
  enable_prompt_for_ai_agents: true
  related_prs: true
  high_level_summary_instructions:
  fail_commit_status: false
  abort_on_close: true
  suggested_labels: true
  auto_apply_labels: false
  auto_assign_reviewers: false
  estimate_code_review_effort: true
  in_progress_fortune: true
  pre_merge_checks:
    { }
  suggested_reviewers: true
  disable_cache: false
  commit_status: true
  high_level_summary_placeholder: "@coderabbitai summary"
  related_issues: true

# Chat configuration
chat:
  auto_reply: true

# Knowledge base - learn from security issues
knowledge_base:
  opt_out: false

  # Enable web search for security advisories
  web_search:
    enabled: true

  # Learn from code guidelines
  code_guidelines:
    enabled: true
    filePatterns:
      - ".specify/memory/constitution.md"
      - "AGENTS.md"

  # Learn from previous issues
  learnings:
    scope: "global"

  # Track security-related issues
  issues:
    scope: "global"

  # Learn from PRs
  pull_requests:
    scope: "global"
