// DO NOT EDIT - Generated by scripts/codegen-constants.ts
// Source of truth: src/core/constants.ts
// Run: yarn codegen:constants

import Foundation

/**
 * Generated constants from TypeScript source of truth.
 * @see src/core/constants.ts
 */
@objc public final class FabricGeneratedConstants: NSObject {

    // MARK: - Allowed Tags
    @objc public static let allowedTags: [String] = [
        "p",
        "div",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "strong",
        "b",
        "em",
        "i",
        "u",
        "s",
        "del",
        "span",
        "br",
        "a",
        "blockquote",
        "pre",
        "ul",
        "ol",
        "li",
    ]

    // MARK: - Allowed Attributes
    @objc public static let allowedAttributes: [String] = [
        "href",
        "class",
    ]

    // MARK: - Allowed Protocols
    @objc public static let allowedProtocols: [String] = [
        "http",
        "https",
        "mailto",
        "tel",
    ]

    // MARK: - Heading Scales
    @objc public static let headingScales: [String: Double] = [
        "h1": 2,
        "h2": 1.5,
        "h3": 1.17,
        "h4": 1,
        "h5": 0.83,
        "h6": 0.67,
    ]

    // MARK: - Named Colors (ARGB format)
    @objc public static let namedColors: [String: UInt32] = [
        "red": 0xFFFF0000,
        "green": 0xFF00FF00,
        "blue": 0xFF0000FF,
        "black": 0xFF000000,
        "white": 0xFFFFFFFF,
        "gray": 0xFF888888,
        "grey": 0xFF888888,
        "orange": 0xFFFFA500,
        "yellow": 0xFFFFFF00,
        "purple": 0xFF800080,
        "cyan": 0xFF00FFFF,
        "magenta": 0xFFFF00FF,
    ]

    // MARK: - Typography
    @objc public static let defaultFontSize: CGFloat = 14
    @objc public static let boldWeights: [String] = ["bold", "700", "800", "900"]

    // MARK: - List Styling
    @objc public static let listIndentPt: CGFloat = 16
    @objc public static let maxListNestingLevel: Int = 3
    @objc public static let bulletMarker: String = "• "
    @objc public static let listMarkerWidthPt: CGFloat = 4

    // MARK: - Spacing
    @objc public static let paragraphSpacingPt: CGFloat = 8

    // MARK: - Links
    @objc public static let linkColor: UInt32 = 0xFF1A73E8

    // MARK: - Helper Functions
    @objc public static func isBoldWeight(_ weight: String?) -> Bool {
        guard let weight = weight else { return false }
        return boldWeights.contains(weight)
    }

    @objc public static func isItalicStyle(_ style: String?) -> Bool {
        return style == "italic"
    }

    @objc public static func parseNamedColor(_ name: String) -> NSNumber? {
        guard let color = namedColors[name.lowercased()] else { return nil }
        return NSNumber(value: color)
    }

    @objc public static func getHeadingScale(_ heading: String) -> CGFloat {
        return headingScales[heading] ?? 1.0
    }
}
