// DO NOT EDIT - Generated by scripts/codegen-constants.ts
// Source of truth: src/core/constants.ts
// Run: yarn codegen:constants

package io.michaelfay.fabricrichtext

/**
 * Generated constants from TypeScript source of truth.
 * @see src/core/constants.ts
 */
object FabricGeneratedConstants {

    // Allowed Tags
    val ALLOWED_TAGS = arrayOf(
        "p",
        "div",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "strong",
        "b",
        "em",
        "i",
        "u",
        "s",
        "del",
        "span",
        "br",
        "a",
        "blockquote",
        "pre",
        "ul",
        "ol",
        "li",
    )

    // Allowed Attributes
    val ALLOWED_ATTRIBUTES = arrayOf(
        "href",
        "class",
    )

    // Allowed Protocols
    val ALLOWED_PROTOCOLS = arrayOf(
        "http",
        "https",
        "mailto",
        "tel",
    )

    // Heading Scales
    val HEADING_SCALES = mapOf(
        "h1" to 2f,
        "h2" to 1.5f,
        "h3" to 1.17f,
        "h4" to 1f,
        "h5" to 0.83f,
        "h6" to 0.67f,
    )

    // Named Colors (ARGB format)
    val NAMED_COLORS = mapOf(
        "red" to 0xFFFF0000.toInt(),
        "green" to 0xFF00FF00.toInt(),
        "blue" to 0xFF0000FF.toInt(),
        "black" to 0xFF000000.toInt(),
        "white" to 0xFFFFFFFF.toInt(),
        "gray" to 0xFF888888.toInt(),
        "grey" to 0xFF888888.toInt(),
        "orange" to 0xFFFFA500.toInt(),
        "yellow" to 0xFFFFFF00.toInt(),
        "purple" to 0xFF800080.toInt(),
        "cyan" to 0xFF00FFFF.toInt(),
        "magenta" to 0xFFFF00FF.toInt(),
    )

    // Typography
    const val DEFAULT_FONT_SIZE = 14f
    val BOLD_WEIGHTS = arrayOf("bold", "700", "800", "900")

    // List Styling
    const val LIST_INDENT_PX = 32
    const val MAX_LIST_NESTING_LEVEL = 3
    const val BULLET_MARKER = "• "

    // Links
    const val LINK_COLOR = 0xFF1A73E8.toInt()

    // Helper Functions
    fun isBoldWeight(weight: String?): Boolean {
        return weight in BOLD_WEIGHTS
    }

    fun isItalicStyle(style: String?): Boolean {
        return style == "italic"
    }

    fun parseNamedColor(name: String): Int? = NAMED_COLORS[name.lowercase()]

    fun getHeadingScale(heading: String): Float = HEADING_SCALES[heading] ?: 1.0f
}
